language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
addons:
  artifacts: true
env:
  - API_KEY=$API_KEY
  - AUTH_DOMAIN=$AUTH_DOMAIN
  - DATABASE_URL=$AUTH_DOMAIN
  - PROJECT_ID=$PROJECT_ID
  - STORAGE_BUCKET=$STORAGE_BUCKET
  - MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
  - APP_ID=$APP_ID
  - MEASUREMENT_ID=$MEASUREMENT_ID
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_acess_key: $AWS_SECRET
  bucket: 'www.sprintman.cf'
  region: eu-central-1
  skip_cleanup: true
  local_dir: build
  acl: public_read
on:
  branch: master
