language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
addons:
  artifacts: true
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_acess_key: $AWS_SECRET
  bucket: 'www.sprintman.cf'
  region: eu-central-1
  skip_cleanup: true
  acl: public_read
on:
  branch: master
