language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_acess_key: $AWS_SECRET
  bucket: 'www.sprintman.cf'
  skip_cleanup: true
  region: eu-central-1
  local_dir: public
