version: '3.7'

services:
  sprint-man:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprint-man.bannersnack.local
    hostname: sprint-man.bannersnack.local
    environment:
      - API_KEY=${API_KEY}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - PROJECT_ID=${PROJECT_ID}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
      - APP_ID=${APP_ID}
      - MEASUREMENT_ID=${MEASUREMENT_ID}
    ports:
      - '80:80'
